//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupaJela
    {
        public GrupaJela()
        {
            this.Jelo = new HashSet<Jelo>();
        }
    
        public int GrupaJelaID { get; set; }
        public string Grupa { get; set; }
    
        public virtual ICollection<Jelo> Jelo { get; set; }
    }
}
