//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JedinicaMjere
    {
        public JedinicaMjere()
        {
            this.Sastojak = new HashSet<Sastojak>();
        }
    
        public int JedinicaMjereID { get; set; }
        public string Jedinica { get; set; }
        public string Kratica { get; set; }
    
        public virtual ICollection<Sastojak> Sastojak { get; set; }
    }
}
