//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Jelo
    {
        public Jelo()
        {
            this.OcjenaJela = new HashSet<OcjenaJela>();
            this.Sastojak = new HashSet<Sastojak>();
            this.Sastojak1 = new HashSet<Sastojak>();
        }
    
        public int JeloID { get; set; }
        [Required(ErrorMessage = "Unesite naziv jela.", AllowEmptyStrings = false)]
        [Display(Name = "Naziv")]
        public string NazivJela { get; set; }

        [Display(Name = "Slika")]
        public byte[] SlikaJela { get; set; }

        [Display(Name = "Grupa jela")]
        public Nullable<int> GrupaJelaID { get; set; }

        [Required(ErrorMessage = "Unesite recept.", AllowEmptyStrings = false)]
        [Display(Name = "Recept")]
        public string Recept { get; set; }
        public Nullable<int> OsobaID { get; set; }
    
        public virtual GrupaJela GrupaJela { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual ICollection<OcjenaJela> OcjenaJela { get; set; }
        public virtual ICollection<Sastojak> Sastojak { get; set; }
        public virtual ICollection<Sastojak> Sastojak1 { get; set; }
    }
}
