//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UpravljanjeRecepturamaBaza : DbContext
    {
        public UpravljanjeRecepturamaBaza()
            : base("name=UpravljanjeRecepturamaBazaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GrupaJela> GrupaJela { get; set; }
        public DbSet<JedinicaMjere> JedinicaMjere { get; set; }
        public DbSet<Jelo> Jelo { get; set; }
        public DbSet<Ocjena> Ocjena { get; set; }
        public DbSet<OcjenaJela> OcjenaJela { get; set; }
        public DbSet<Osoba> Osoba { get; set; }
        public DbSet<Sastojak> Sastojak { get; set; }
    }
}
