//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OcjenaJela
    {
        public int OcjenaJelaID { get; set; }
        public int OsobaID { get; set; }
        public int JeloID { get; set; }
        [Required(ErrorMessage = "Odaberite ocjenu.", AllowEmptyStrings = false)]
        public int OcjenaID { get; set; }
    
        public virtual Jelo Jelo { get; set; }
        public virtual Ocjena Ocjena { get; set; }
        public virtual Osoba Osoba { get; set; }
    }
}
