//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjena
    {
        public Ocjena()
        {
            this.OcjenaJela = new HashSet<OcjenaJela>();
        }
    
        public int OcjenaID { get; set; }
        public int Vrijednost { get; set; }
    
        public virtual ICollection<OcjenaJela> OcjenaJela { get; set; }
    }
}
