//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Osoba
    {
        public Osoba()
        {
            this.Jelo = new HashSet<Jelo>();
            this.OcjenaJela = new HashSet<OcjenaJela>();
        }

        public int OsobaID { get; set; }

        [Required(ErrorMessage = "Unesite ime.", AllowEmptyStrings = false)]
        public string Ime { get; set; }

        [Required(ErrorMessage = "Unesite prezime.", AllowEmptyStrings = false)]
        public string Prezime { get; set; }

        [Required(ErrorMessage = "Unesite email.", AllowEmptyStrings = false)]
        [RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
                    ErrorMessage = "Email adresa nije valjana.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Unesite lozinku.", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(200, MinimumLength = 6, ErrorMessage = "Lozinka mora imati najmanje 6 znakova.")]
        public string Lozinka { get; set; }

        public string Salt { get; set; }

        public virtual ICollection<Jelo> Jelo { get; set; }
        public virtual ICollection<OcjenaJela> OcjenaJela { get; set; }
    }
}
