//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavrsniRad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sastojak
    {
        public int SastojakID { get; set; }
        public int JeloID { get; set; }
        public decimal Kolicina { get; set; }
        public Nullable<int> JedinicaMjereID { get; set; }
    
        public virtual JedinicaMjere JedinicaMjere { get; set; }
        public virtual Jelo Jelo { get; set; }
        public virtual Jelo Jelo1 { get; set; }
    }
}
